### ISSUE TITLE
[Feature] Save to the disk for seeding

### ISSUE THREAD

**Issue by oformaniuk** [YouROK/TorrServer#134]
Nowadays less and less people do torrent seeding and more prefer torrent streaming instead. 
Unfortunately, this dramatically affects number of seeders and download speeds as a result.

Proposal: optional long-term seeding.
In addition to cache configuration add an option to store files on disk for further seeding. For better user experience - delete files by some criteria (oldest, by seeders count, etc.) once there is no free space left (or files size exceeds configured threshold).

**Comment by crzsotona** [comment]
Just use BiglyBT or Transmission in parallel.

**Comment by oformaniuk** [comment]
@crzsotona, the whole point is to make experience seamless. I (and most probably other users) would not bother adding download to another client separately if they use their TV to add torrent at the first place.

**Comment by aabytt** [comment]
> @crzsotona, the whole point is to make experience seamless. I (and most probably other users) would not bother adding download to another client separately if they use their TV to add torrent at the first place.

Made it kind of seamless by adding a function to a client web app I use with torrserver on my LG webOS TV.
As soon as I add torrent from app's search results it also adds torrent to transmission daemon running on remote NAS which is scheduled to download and seed. This way I can also download old torrents that do not have enough seeds for streaming so that to watch them later with DLNA from the same NAS. 
Cons:
scheme does not use Torrserver's cache data and torrent is actually downloaded twice.

**Comment by YouROK** [comment]
For this case you can use bit torrent clients

**Comment by yozik04** [comment]
To use an another bit torrent client we need a feature to download torrent file or get a magnet link.

**Comment by yozik04** [comment]
Hmm, torrent hash actually can act as a magnet link, but trackers are not defined this way. So TV and separate torrent client can not find each other...
