### ISSUE TITLE
[Feature] Add a configurable threshold for seen/unseen

### ISSUE THREAD

**Issue by cocool97** [YouROK/TorrServer#305]
Currently seen / unseen is set at first torrent watch. A threshold could be implemented, and torrent would be considered seen above it.

Like for exemple by default 85% of the total view length.

**Comment by YouROK** [comment]
It's hard to do, and you have to memorize what you read when you open the reader from the player. The player is constantly reading the first chunks and the last chunks for video information.
You can watch when closing the reader at what point he stopped at say 83% closed the movie. But it can enter the piece where there is information, both at the beginning and at the end. And at the same time may not have not watched the movie at all, but only received information and it was just in this percentage.
Another point, the player has its own buffer. It turns out that viewing can be stopped at 50% of viewed, and the buffer is already downloaded to 100%
I'll try to make if the reader stopped between 70 and 95, then add a label about viewing

Это трудно сделать, и приходится запоминать прочитанное, когда открывается ридер из плеера. При этом плеер постоянно читает первые куски и последние куски для информации о видео.
Можно смотреть при закрытии ридера на каком он моменте остановился допустим на 83% закрыли фильм. Но это может войти в кусок где находится информация, как в начале так и в конце. И при этом может быть совсем не смотрели фильм, а только получена информация и она как раз находилась в этом проценте.
Еще один момент, плеер имеет свой буфер. Получается что просмотр может быть остановлен на 50% просмотренного, а буфер уже закачался на все 100%
Попробую сделать если ридер остановился в пределах от 70 до 95 то добавлять метку о просмотре

**Comment by YouROK** [comment]
Looked at how it works, it doesn't work very well. Since the reader does not interrupt and reads to the end 100%
And in the cache itself it would be too expensive to put a mark of viewing. I'll leave it as it was.
